version: "3"

networks:
  web:
    external: true
  djangonetwork:
    driver: bridge

services:
  app:
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    build: .
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    labels:
      - traefik.backend=app
      - traefik.frontend.rule=Host:sdmitriev.pro
      - traefik.docker.network=web
      - traefik.port=8000
    networks:
      - web
      - djangonetwork
  db:
    image: postgres:15
    container_name: db
    networks:
      - djangonetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data: