version: "3"

services:
  app:
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    labels:
      - traefik.backend=app
      - traefik.frontend.rule=Host:sdmitriev.pro
      - traefik.docker.network=web
      - traefik.port=8000